// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v7.36.2
// source: engram.proto

package engrampb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type MemoryRecord struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Namespace      string                 `protobuf:"bytes,1,opt,name=namespace,proto3" json:"namespace,omitempty"`
	Key            string                 `protobuf:"bytes,2,opt,name=key,proto3" json:"key,omitempty"`
	Value          []byte                 `protobuf:"bytes,3,opt,name=value,proto3" json:"value,omitempty"`
	Version        uint64                 `protobuf:"varint,4,opt,name=version,proto3" json:"version,omitempty"`
	CreatedBy      string                 `protobuf:"bytes,5,opt,name=created_by,json=createdBy,proto3" json:"created_by,omitempty"`
	Source         string                 `protobuf:"bytes,6,opt,name=source,proto3" json:"source,omitempty"`
	Confidence     float32                `protobuf:"fixed32,7,opt,name=confidence,proto3" json:"confidence,omitempty"`
	CreatedAt      *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt      *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	ExpiresAt      *timestamppb.Timestamp `protobuf:"bytes,10,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`
	LastAccessedAt *timestamppb.Timestamp `protobuf:"bytes,11,opt,name=last_accessed_at,json=lastAccessedAt,proto3" json:"last_accessed_at,omitempty"`
	AccessCount    uint64                 `protobuf:"varint,12,opt,name=access_count,json=accessCount,proto3" json:"access_count,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *MemoryRecord) Reset() {
	*x = MemoryRecord{}
	mi := &file_engram_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MemoryRecord) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MemoryRecord) ProtoMessage() {}

func (x *MemoryRecord) ProtoReflect() protoreflect.Message {
	mi := &file_engram_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MemoryRecord.ProtoReflect.Descriptor instead.
func (*MemoryRecord) Descriptor() ([]byte, []int) {
	return file_engram_proto_rawDescGZIP(), []int{0}
}

func (x *MemoryRecord) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *MemoryRecord) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *MemoryRecord) GetValue() []byte {
	if x != nil {
		return x.Value
	}
	return nil
}

func (x *MemoryRecord) GetVersion() uint64 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *MemoryRecord) GetCreatedBy() string {
	if x != nil {
		return x.CreatedBy
	}
	return ""
}

func (x *MemoryRecord) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

func (x *MemoryRecord) GetConfidence() float32 {
	if x != nil {
		return x.Confidence
	}
	return 0
}

func (x *MemoryRecord) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *MemoryRecord) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

func (x *MemoryRecord) GetExpiresAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ExpiresAt
	}
	return nil
}

func (x *MemoryRecord) GetLastAccessedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.LastAccessedAt
	}
	return nil
}

func (x *MemoryRecord) GetAccessCount() uint64 {
	if x != nil {
		return x.AccessCount
	}
	return 0
}

type Command struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	Timestamp *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	// Types that are valid to be assigned to Payload:
	//
	//	*Command_Put
	//	*Command_CompareAndSet
	//	*Command_Delete
	Payload       isCommand_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Command) Reset() {
	*x = Command{}
	mi := &file_engram_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Command) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Command) ProtoMessage() {}

func (x *Command) ProtoReflect() protoreflect.Message {
	mi := &file_engram_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Command.ProtoReflect.Descriptor instead.
func (*Command) Descriptor() ([]byte, []int) {
	return file_engram_proto_rawDescGZIP(), []int{1}
}

func (x *Command) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

func (x *Command) GetPayload() isCommand_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *Command) GetPut() *PutCommand {
	if x != nil {
		if x, ok := x.Payload.(*Command_Put); ok {
			return x.Put
		}
	}
	return nil
}

func (x *Command) GetCompareAndSet() *CompareAndSetCommand {
	if x != nil {
		if x, ok := x.Payload.(*Command_CompareAndSet); ok {
			return x.CompareAndSet
		}
	}
	return nil
}

func (x *Command) GetDelete() *DeleteCommand {
	if x != nil {
		if x, ok := x.Payload.(*Command_Delete); ok {
			return x.Delete
		}
	}
	return nil
}

type isCommand_Payload interface {
	isCommand_Payload()
}

type Command_Put struct {
	Put *PutCommand `protobuf:"bytes,2,opt,name=put,proto3,oneof"`
}

type Command_CompareAndSet struct {
	CompareAndSet *CompareAndSetCommand `protobuf:"bytes,3,opt,name=compare_and_set,json=compareAndSet,proto3,oneof"`
}

type Command_Delete struct {
	Delete *DeleteCommand `protobuf:"bytes,4,opt,name=delete,proto3,oneof"`
}

func (*Command_Put) isCommand_Payload() {}

func (*Command_CompareAndSet) isCommand_Payload() {}

func (*Command_Delete) isCommand_Payload() {}

type PutCommand struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Namespace     string                 `protobuf:"bytes,1,opt,name=namespace,proto3" json:"namespace,omitempty"`
	Key           string                 `protobuf:"bytes,2,opt,name=key,proto3" json:"key,omitempty"`
	Value         []byte                 `protobuf:"bytes,3,opt,name=value,proto3" json:"value,omitempty"`
	CreatedBy     string                 `protobuf:"bytes,4,opt,name=created_by,json=createdBy,proto3" json:"created_by,omitempty"`
	Source        string                 `protobuf:"bytes,5,opt,name=source,proto3" json:"source,omitempty"`
	Confidence    float32                `protobuf:"fixed32,6,opt,name=confidence,proto3" json:"confidence,omitempty"`
	ExpiresAt     *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PutCommand) Reset() {
	*x = PutCommand{}
	mi := &file_engram_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PutCommand) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PutCommand) ProtoMessage() {}

func (x *PutCommand) ProtoReflect() protoreflect.Message {
	mi := &file_engram_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PutCommand.ProtoReflect.Descriptor instead.
func (*PutCommand) Descriptor() ([]byte, []int) {
	return file_engram_proto_rawDescGZIP(), []int{2}
}

func (x *PutCommand) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *PutCommand) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *PutCommand) GetValue() []byte {
	if x != nil {
		return x.Value
	}
	return nil
}

func (x *PutCommand) GetCreatedBy() string {
	if x != nil {
		return x.CreatedBy
	}
	return ""
}

func (x *PutCommand) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

func (x *PutCommand) GetConfidence() float32 {
	if x != nil {
		return x.Confidence
	}
	return 0
}

func (x *PutCommand) GetExpiresAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ExpiresAt
	}
	return nil
}

type CompareAndSetCommand struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Namespace       string                 `protobuf:"bytes,1,opt,name=namespace,proto3" json:"namespace,omitempty"`
	Key             string                 `protobuf:"bytes,2,opt,name=key,proto3" json:"key,omitempty"`
	Value           []byte                 `protobuf:"bytes,3,opt,name=value,proto3" json:"value,omitempty"`
	ExpectedVersion uint64                 `protobuf:"varint,4,opt,name=expected_version,json=expectedVersion,proto3" json:"expected_version,omitempty"`
	CreatedBy       string                 `protobuf:"bytes,5,opt,name=created_by,json=createdBy,proto3" json:"created_by,omitempty"`
	Source          string                 `protobuf:"bytes,6,opt,name=source,proto3" json:"source,omitempty"`
	Confidence      float32                `protobuf:"fixed32,7,opt,name=confidence,proto3" json:"confidence,omitempty"`
	ExpiresAt       *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *CompareAndSetCommand) Reset() {
	*x = CompareAndSetCommand{}
	mi := &file_engram_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CompareAndSetCommand) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CompareAndSetCommand) ProtoMessage() {}

func (x *CompareAndSetCommand) ProtoReflect() protoreflect.Message {
	mi := &file_engram_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CompareAndSetCommand.ProtoReflect.Descriptor instead.
func (*CompareAndSetCommand) Descriptor() ([]byte, []int) {
	return file_engram_proto_rawDescGZIP(), []int{3}
}

func (x *CompareAndSetCommand) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *CompareAndSetCommand) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *CompareAndSetCommand) GetValue() []byte {
	if x != nil {
		return x.Value
	}
	return nil
}

func (x *CompareAndSetCommand) GetExpectedVersion() uint64 {
	if x != nil {
		return x.ExpectedVersion
	}
	return 0
}

func (x *CompareAndSetCommand) GetCreatedBy() string {
	if x != nil {
		return x.CreatedBy
	}
	return ""
}

func (x *CompareAndSetCommand) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

func (x *CompareAndSetCommand) GetConfidence() float32 {
	if x != nil {
		return x.Confidence
	}
	return 0
}

func (x *CompareAndSetCommand) GetExpiresAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ExpiresAt
	}
	return nil
}

type DeleteCommand struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Namespace       string                 `protobuf:"bytes,1,opt,name=namespace,proto3" json:"namespace,omitempty"`
	Key             string                 `protobuf:"bytes,2,opt,name=key,proto3" json:"key,omitempty"`
	ExpectedVersion uint64                 `protobuf:"varint,3,opt,name=expected_version,json=expectedVersion,proto3" json:"expected_version,omitempty"` // 0 = unconditional
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *DeleteCommand) Reset() {
	*x = DeleteCommand{}
	mi := &file_engram_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteCommand) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteCommand) ProtoMessage() {}

func (x *DeleteCommand) ProtoReflect() protoreflect.Message {
	mi := &file_engram_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteCommand.ProtoReflect.Descriptor instead.
func (*DeleteCommand) Descriptor() ([]byte, []int) {
	return file_engram_proto_rawDescGZIP(), []int{4}
}

func (x *DeleteCommand) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *DeleteCommand) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *DeleteCommand) GetExpectedVersion() uint64 {
	if x != nil {
		return x.ExpectedVersion
	}
	return 0
}

// Apply returns this. Not in the Raft log, just the response.
type CommandResult struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Result:
	//
	//	*CommandResult_Mutation
	//	*CommandResult_DeleteResult
	//	*CommandResult_CasConflict
	Result        isCommandResult_Result `protobuf_oneof:"result"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CommandResult) Reset() {
	*x = CommandResult{}
	mi := &file_engram_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommandResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommandResult) ProtoMessage() {}

func (x *CommandResult) ProtoReflect() protoreflect.Message {
	mi := &file_engram_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommandResult.ProtoReflect.Descriptor instead.
func (*CommandResult) Descriptor() ([]byte, []int) {
	return file_engram_proto_rawDescGZIP(), []int{5}
}

func (x *CommandResult) GetResult() isCommandResult_Result {
	if x != nil {
		return x.Result
	}
	return nil
}

func (x *CommandResult) GetMutation() *MutationResult {
	if x != nil {
		if x, ok := x.Result.(*CommandResult_Mutation); ok {
			return x.Mutation
		}
	}
	return nil
}

func (x *CommandResult) GetDeleteResult() *DeleteResult {
	if x != nil {
		if x, ok := x.Result.(*CommandResult_DeleteResult); ok {
			return x.DeleteResult
		}
	}
	return nil
}

func (x *CommandResult) GetCasConflict() *CASConflict {
	if x != nil {
		if x, ok := x.Result.(*CommandResult_CasConflict); ok {
			return x.CasConflict
		}
	}
	return nil
}

type isCommandResult_Result interface {
	isCommandResult_Result()
}

type CommandResult_Mutation struct {
	Mutation *MutationResult `protobuf:"bytes,1,opt,name=mutation,proto3,oneof"`
}

type CommandResult_DeleteResult struct {
	DeleteResult *DeleteResult `protobuf:"bytes,2,opt,name=delete_result,json=deleteResult,proto3,oneof"`
}

type CommandResult_CasConflict struct {
	CasConflict *CASConflict `protobuf:"bytes,3,opt,name=cas_conflict,json=casConflict,proto3,oneof"`
}

func (*CommandResult_Mutation) isCommandResult_Result() {}

func (*CommandResult_DeleteResult) isCommandResult_Result() {}

func (*CommandResult_CasConflict) isCommandResult_Result() {}

type MutationResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Version       uint64                 `protobuf:"varint,1,opt,name=version,proto3" json:"version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MutationResult) Reset() {
	*x = MutationResult{}
	mi := &file_engram_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MutationResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MutationResult) ProtoMessage() {}

func (x *MutationResult) ProtoReflect() protoreflect.Message {
	mi := &file_engram_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MutationResult.ProtoReflect.Descriptor instead.
func (*MutationResult) Descriptor() ([]byte, []int) {
	return file_engram_proto_rawDescGZIP(), []int{6}
}

func (x *MutationResult) GetVersion() uint64 {
	if x != nil {
		return x.Version
	}
	return 0
}

type DeleteResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteResult) Reset() {
	*x = DeleteResult{}
	mi := &file_engram_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteResult) ProtoMessage() {}

func (x *DeleteResult) ProtoReflect() protoreflect.Message {
	mi := &file_engram_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteResult.ProtoReflect.Descriptor instead.
func (*DeleteResult) Descriptor() ([]byte, []int) {
	return file_engram_proto_rawDescGZIP(), []int{7}
}

type CASConflict struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	CurrentVersion uint64                 `protobuf:"varint,1,opt,name=current_version,json=currentVersion,proto3" json:"current_version,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *CASConflict) Reset() {
	*x = CASConflict{}
	mi := &file_engram_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CASConflict) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CASConflict) ProtoMessage() {}

func (x *CASConflict) ProtoReflect() protoreflect.Message {
	mi := &file_engram_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CASConflict.ProtoReflect.Descriptor instead.
func (*CASConflict) Descriptor() ([]byte, []int) {
	return file_engram_proto_rawDescGZIP(), []int{8}
}

func (x *CASConflict) GetCurrentVersion() uint64 {
	if x != nil {
		return x.CurrentVersion
	}
	return 0
}

type PutRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Namespace     string                 `protobuf:"bytes,1,opt,name=namespace,proto3" json:"namespace,omitempty"`
	Key           string                 `protobuf:"bytes,2,opt,name=key,proto3" json:"key,omitempty"`
	Value         []byte                 `protobuf:"bytes,3,opt,name=value,proto3" json:"value,omitempty"`
	CreatedBy     string                 `protobuf:"bytes,4,opt,name=created_by,json=createdBy,proto3" json:"created_by,omitempty"`
	Source        string                 `protobuf:"bytes,5,opt,name=source,proto3" json:"source,omitempty"`
	Confidence    float32                `protobuf:"fixed32,6,opt,name=confidence,proto3" json:"confidence,omitempty"`
	ExpiresAt     *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PutRequest) Reset() {
	*x = PutRequest{}
	mi := &file_engram_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PutRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PutRequest) ProtoMessage() {}

func (x *PutRequest) ProtoReflect() protoreflect.Message {
	mi := &file_engram_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PutRequest.ProtoReflect.Descriptor instead.
func (*PutRequest) Descriptor() ([]byte, []int) {
	return file_engram_proto_rawDescGZIP(), []int{9}
}

func (x *PutRequest) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *PutRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *PutRequest) GetValue() []byte {
	if x != nil {
		return x.Value
	}
	return nil
}

func (x *PutRequest) GetCreatedBy() string {
	if x != nil {
		return x.CreatedBy
	}
	return ""
}

func (x *PutRequest) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

func (x *PutRequest) GetConfidence() float32 {
	if x != nil {
		return x.Confidence
	}
	return 0
}

func (x *PutRequest) GetExpiresAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ExpiresAt
	}
	return nil
}

type PutResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Version       uint64                 `protobuf:"varint,1,opt,name=version,proto3" json:"version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PutResponse) Reset() {
	*x = PutResponse{}
	mi := &file_engram_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PutResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PutResponse) ProtoMessage() {}

func (x *PutResponse) ProtoReflect() protoreflect.Message {
	mi := &file_engram_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PutResponse.ProtoReflect.Descriptor instead.
func (*PutResponse) Descriptor() ([]byte, []int) {
	return file_engram_proto_rawDescGZIP(), []int{10}
}

func (x *PutResponse) GetVersion() uint64 {
	if x != nil {
		return x.Version
	}
	return 0
}

type GetRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Namespace     string                 `protobuf:"bytes,1,opt,name=namespace,proto3" json:"namespace,omitempty"`
	Key           string                 `protobuf:"bytes,2,opt,name=key,proto3" json:"key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRequest) Reset() {
	*x = GetRequest{}
	mi := &file_engram_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRequest) ProtoMessage() {}

func (x *GetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_engram_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRequest.ProtoReflect.Descriptor instead.
func (*GetRequest) Descriptor() ([]byte, []int) {
	return file_engram_proto_rawDescGZIP(), []int{11}
}

func (x *GetRequest) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *GetRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

type GetResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Record        *MemoryRecord          `protobuf:"bytes,1,opt,name=record,proto3" json:"record,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetResponse) Reset() {
	*x = GetResponse{}
	mi := &file_engram_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetResponse) ProtoMessage() {}

func (x *GetResponse) ProtoReflect() protoreflect.Message {
	mi := &file_engram_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetResponse.ProtoReflect.Descriptor instead.
func (*GetResponse) Descriptor() ([]byte, []int) {
	return file_engram_proto_rawDescGZIP(), []int{12}
}

func (x *GetResponse) GetRecord() *MemoryRecord {
	if x != nil {
		return x.Record
	}
	return nil
}

type CompareAndSetRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Namespace       string                 `protobuf:"bytes,1,opt,name=namespace,proto3" json:"namespace,omitempty"`
	Key             string                 `protobuf:"bytes,2,opt,name=key,proto3" json:"key,omitempty"`
	Value           []byte                 `protobuf:"bytes,3,opt,name=value,proto3" json:"value,omitempty"`
	ExpectedVersion uint64                 `protobuf:"varint,4,opt,name=expected_version,json=expectedVersion,proto3" json:"expected_version,omitempty"`
	CreatedBy       string                 `protobuf:"bytes,5,opt,name=created_by,json=createdBy,proto3" json:"created_by,omitempty"`
	Source          string                 `protobuf:"bytes,6,opt,name=source,proto3" json:"source,omitempty"`
	Confidence      float32                `protobuf:"fixed32,7,opt,name=confidence,proto3" json:"confidence,omitempty"`
	ExpiresAt       *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *CompareAndSetRequest) Reset() {
	*x = CompareAndSetRequest{}
	mi := &file_engram_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CompareAndSetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CompareAndSetRequest) ProtoMessage() {}

func (x *CompareAndSetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_engram_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CompareAndSetRequest.ProtoReflect.Descriptor instead.
func (*CompareAndSetRequest) Descriptor() ([]byte, []int) {
	return file_engram_proto_rawDescGZIP(), []int{13}
}

func (x *CompareAndSetRequest) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *CompareAndSetRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *CompareAndSetRequest) GetValue() []byte {
	if x != nil {
		return x.Value
	}
	return nil
}

func (x *CompareAndSetRequest) GetExpectedVersion() uint64 {
	if x != nil {
		return x.ExpectedVersion
	}
	return 0
}

func (x *CompareAndSetRequest) GetCreatedBy() string {
	if x != nil {
		return x.CreatedBy
	}
	return ""
}

func (x *CompareAndSetRequest) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

func (x *CompareAndSetRequest) GetConfidence() float32 {
	if x != nil {
		return x.Confidence
	}
	return 0
}

func (x *CompareAndSetRequest) GetExpiresAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ExpiresAt
	}
	return nil
}

type CompareAndSetResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Version       uint64                 `protobuf:"varint,1,opt,name=version,proto3" json:"version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CompareAndSetResponse) Reset() {
	*x = CompareAndSetResponse{}
	mi := &file_engram_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CompareAndSetResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CompareAndSetResponse) ProtoMessage() {}

func (x *CompareAndSetResponse) ProtoReflect() protoreflect.Message {
	mi := &file_engram_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CompareAndSetResponse.ProtoReflect.Descriptor instead.
func (*CompareAndSetResponse) Descriptor() ([]byte, []int) {
	return file_engram_proto_rawDescGZIP(), []int{14}
}

func (x *CompareAndSetResponse) GetVersion() uint64 {
	if x != nil {
		return x.Version
	}
	return 0
}

type DeleteRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Namespace       string                 `protobuf:"bytes,1,opt,name=namespace,proto3" json:"namespace,omitempty"`
	Key             string                 `protobuf:"bytes,2,opt,name=key,proto3" json:"key,omitempty"`
	ExpectedVersion uint64                 `protobuf:"varint,3,opt,name=expected_version,json=expectedVersion,proto3" json:"expected_version,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *DeleteRequest) Reset() {
	*x = DeleteRequest{}
	mi := &file_engram_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteRequest) ProtoMessage() {}

func (x *DeleteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_engram_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteRequest.ProtoReflect.Descriptor instead.
func (*DeleteRequest) Descriptor() ([]byte, []int) {
	return file_engram_proto_rawDescGZIP(), []int{15}
}

func (x *DeleteRequest) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *DeleteRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *DeleteRequest) GetExpectedVersion() uint64 {
	if x != nil {
		return x.ExpectedVersion
	}
	return 0
}

type DeleteResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteResponse) Reset() {
	*x = DeleteResponse{}
	mi := &file_engram_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteResponse) ProtoMessage() {}

func (x *DeleteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_engram_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteResponse.ProtoReflect.Descriptor instead.
func (*DeleteResponse) Descriptor() ([]byte, []int) {
	return file_engram_proto_rawDescGZIP(), []int{16}
}

type ListRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Namespace     string                 `protobuf:"bytes,1,opt,name=namespace,proto3" json:"namespace,omitempty"`
	KeyPrefix     string                 `protobuf:"bytes,2,opt,name=key_prefix,json=keyPrefix,proto3" json:"key_prefix,omitempty"`
	Limit         int32                  `protobuf:"varint,3,opt,name=limit,proto3" json:"limit,omitempty"`
	PageToken     string                 `protobuf:"bytes,4,opt,name=page_token,json=pageToken,proto3" json:"page_token,omitempty"` // opaque; encodes last key seen
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListRequest) Reset() {
	*x = ListRequest{}
	mi := &file_engram_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListRequest) ProtoMessage() {}

func (x *ListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_engram_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListRequest.ProtoReflect.Descriptor instead.
func (*ListRequest) Descriptor() ([]byte, []int) {
	return file_engram_proto_rawDescGZIP(), []int{17}
}

func (x *ListRequest) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *ListRequest) GetKeyPrefix() string {
	if x != nil {
		return x.KeyPrefix
	}
	return ""
}

func (x *ListRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *ListRequest) GetPageToken() string {
	if x != nil {
		return x.PageToken
	}
	return ""
}

type ListResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Records       []*MemoryRecord        `protobuf:"bytes,1,rep,name=records,proto3" json:"records,omitempty"`
	NextPageToken string                 `protobuf:"bytes,2,opt,name=next_page_token,json=nextPageToken,proto3" json:"next_page_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListResponse) Reset() {
	*x = ListResponse{}
	mi := &file_engram_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListResponse) ProtoMessage() {}

func (x *ListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_engram_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListResponse.ProtoReflect.Descriptor instead.
func (*ListResponse) Descriptor() ([]byte, []int) {
	return file_engram_proto_rawDescGZIP(), []int{18}
}

func (x *ListResponse) GetRecords() []*MemoryRecord {
	if x != nil {
		return x.Records
	}
	return nil
}

func (x *ListResponse) GetNextPageToken() string {
	if x != nil {
		return x.NextPageToken
	}
	return ""
}

var File_engram_proto protoreflect.FileDescriptor

const file_engram_proto_rawDesc = "" +
	"\n" +
	"\fengram.proto\x12\tengram.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"\xdf\x03\n" +
	"\fMemoryRecord\x12\x1c\n" +
	"\tnamespace\x18\x01 \x01(\tR\tnamespace\x12\x10\n" +
	"\x03key\x18\x02 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x03 \x01(\fR\x05value\x12\x18\n" +
	"\aversion\x18\x04 \x01(\x04R\aversion\x12\x1d\n" +
	"\n" +
	"created_by\x18\x05 \x01(\tR\tcreatedBy\x12\x16\n" +
	"\x06source\x18\x06 \x01(\tR\x06source\x12\x1e\n" +
	"\n" +
	"confidence\x18\a \x01(\x02R\n" +
	"confidence\x129\n" +
	"\n" +
	"created_at\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\t \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\x129\n" +
	"\n" +
	"expires_at\x18\n" +
	" \x01(\v2\x1a.google.protobuf.TimestampR\texpiresAt\x12D\n" +
	"\x10last_accessed_at\x18\v \x01(\v2\x1a.google.protobuf.TimestampR\x0elastAccessedAt\x12!\n" +
	"\faccess_count\x18\f \x01(\x04R\vaccessCount\"\xf8\x01\n" +
	"\aCommand\x128\n" +
	"\ttimestamp\x18\x01 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\x12)\n" +
	"\x03put\x18\x02 \x01(\v2\x15.engram.v1.PutCommandH\x00R\x03put\x12I\n" +
	"\x0fcompare_and_set\x18\x03 \x01(\v2\x1f.engram.v1.CompareAndSetCommandH\x00R\rcompareAndSet\x122\n" +
	"\x06delete\x18\x04 \x01(\v2\x18.engram.v1.DeleteCommandH\x00R\x06deleteB\t\n" +
	"\apayload\"\xe4\x01\n" +
	"\n" +
	"PutCommand\x12\x1c\n" +
	"\tnamespace\x18\x01 \x01(\tR\tnamespace\x12\x10\n" +
	"\x03key\x18\x02 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x03 \x01(\fR\x05value\x12\x1d\n" +
	"\n" +
	"created_by\x18\x04 \x01(\tR\tcreatedBy\x12\x16\n" +
	"\x06source\x18\x05 \x01(\tR\x06source\x12\x1e\n" +
	"\n" +
	"confidence\x18\x06 \x01(\x02R\n" +
	"confidence\x129\n" +
	"\n" +
	"expires_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\texpiresAt\"\x99\x02\n" +
	"\x14CompareAndSetCommand\x12\x1c\n" +
	"\tnamespace\x18\x01 \x01(\tR\tnamespace\x12\x10\n" +
	"\x03key\x18\x02 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x03 \x01(\fR\x05value\x12)\n" +
	"\x10expected_version\x18\x04 \x01(\x04R\x0fexpectedVersion\x12\x1d\n" +
	"\n" +
	"created_by\x18\x05 \x01(\tR\tcreatedBy\x12\x16\n" +
	"\x06source\x18\x06 \x01(\tR\x06source\x12\x1e\n" +
	"\n" +
	"confidence\x18\a \x01(\x02R\n" +
	"confidence\x129\n" +
	"\n" +
	"expires_at\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\texpiresAt\"j\n" +
	"\rDeleteCommand\x12\x1c\n" +
	"\tnamespace\x18\x01 \x01(\tR\tnamespace\x12\x10\n" +
	"\x03key\x18\x02 \x01(\tR\x03key\x12)\n" +
	"\x10expected_version\x18\x03 \x01(\x04R\x0fexpectedVersion\"\xcf\x01\n" +
	"\rCommandResult\x127\n" +
	"\bmutation\x18\x01 \x01(\v2\x19.engram.v1.MutationResultH\x00R\bmutation\x12>\n" +
	"\rdelete_result\x18\x02 \x01(\v2\x17.engram.v1.DeleteResultH\x00R\fdeleteResult\x12;\n" +
	"\fcas_conflict\x18\x03 \x01(\v2\x16.engram.v1.CASConflictH\x00R\vcasConflictB\b\n" +
	"\x06result\"*\n" +
	"\x0eMutationResult\x12\x18\n" +
	"\aversion\x18\x01 \x01(\x04R\aversion\"\x0e\n" +
	"\fDeleteResult\"6\n" +
	"\vCASConflict\x12'\n" +
	"\x0fcurrent_version\x18\x01 \x01(\x04R\x0ecurrentVersion\"\xe4\x01\n" +
	"\n" +
	"PutRequest\x12\x1c\n" +
	"\tnamespace\x18\x01 \x01(\tR\tnamespace\x12\x10\n" +
	"\x03key\x18\x02 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x03 \x01(\fR\x05value\x12\x1d\n" +
	"\n" +
	"created_by\x18\x04 \x01(\tR\tcreatedBy\x12\x16\n" +
	"\x06source\x18\x05 \x01(\tR\x06source\x12\x1e\n" +
	"\n" +
	"confidence\x18\x06 \x01(\x02R\n" +
	"confidence\x129\n" +
	"\n" +
	"expires_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\texpiresAt\"'\n" +
	"\vPutResponse\x12\x18\n" +
	"\aversion\x18\x01 \x01(\x04R\aversion\"<\n" +
	"\n" +
	"GetRequest\x12\x1c\n" +
	"\tnamespace\x18\x01 \x01(\tR\tnamespace\x12\x10\n" +
	"\x03key\x18\x02 \x01(\tR\x03key\">\n" +
	"\vGetResponse\x12/\n" +
	"\x06record\x18\x01 \x01(\v2\x17.engram.v1.MemoryRecordR\x06record\"\x99\x02\n" +
	"\x14CompareAndSetRequest\x12\x1c\n" +
	"\tnamespace\x18\x01 \x01(\tR\tnamespace\x12\x10\n" +
	"\x03key\x18\x02 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x03 \x01(\fR\x05value\x12)\n" +
	"\x10expected_version\x18\x04 \x01(\x04R\x0fexpectedVersion\x12\x1d\n" +
	"\n" +
	"created_by\x18\x05 \x01(\tR\tcreatedBy\x12\x16\n" +
	"\x06source\x18\x06 \x01(\tR\x06source\x12\x1e\n" +
	"\n" +
	"confidence\x18\a \x01(\x02R\n" +
	"confidence\x129\n" +
	"\n" +
	"expires_at\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\texpiresAt\"1\n" +
	"\x15CompareAndSetResponse\x12\x18\n" +
	"\aversion\x18\x01 \x01(\x04R\aversion\"j\n" +
	"\rDeleteRequest\x12\x1c\n" +
	"\tnamespace\x18\x01 \x01(\tR\tnamespace\x12\x10\n" +
	"\x03key\x18\x02 \x01(\tR\x03key\x12)\n" +
	"\x10expected_version\x18\x03 \x01(\x04R\x0fexpectedVersion\"\x10\n" +
	"\x0eDeleteResponse\"\x7f\n" +
	"\vListRequest\x12\x1c\n" +
	"\tnamespace\x18\x01 \x01(\tR\tnamespace\x12\x1d\n" +
	"\n" +
	"key_prefix\x18\x02 \x01(\tR\tkeyPrefix\x12\x14\n" +
	"\x05limit\x18\x03 \x01(\x05R\x05limit\x12\x1d\n" +
	"\n" +
	"page_token\x18\x04 \x01(\tR\tpageToken\"i\n" +
	"\fListResponse\x121\n" +
	"\arecords\x18\x01 \x03(\v2\x17.engram.v1.MemoryRecordR\arecords\x12&\n" +
	"\x0fnext_page_token\x18\x02 \x01(\tR\rnextPageToken2\xc7\x02\n" +
	"\rMemoryService\x124\n" +
	"\x03Put\x12\x15.engram.v1.PutRequest\x1a\x16.engram.v1.PutResponse\x124\n" +
	"\x03Get\x12\x15.engram.v1.GetRequest\x1a\x16.engram.v1.GetResponse\x12R\n" +
	"\rCompareAndSet\x12\x1f.engram.v1.CompareAndSetRequest\x1a .engram.v1.CompareAndSetResponse\x12=\n" +
	"\x06Delete\x12\x18.engram.v1.DeleteRequest\x1a\x19.engram.v1.DeleteResponse\x127\n" +
	"\x04List\x12\x16.engram.v1.ListRequest\x1a\x17.engram.v1.ListResponseB*Z(github.com/shrec21/engram/proto/engrampbb\x06proto3"

var (
	file_engram_proto_rawDescOnce sync.Once
	file_engram_proto_rawDescData []byte
)

func file_engram_proto_rawDescGZIP() []byte {
	file_engram_proto_rawDescOnce.Do(func() {
		file_engram_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_engram_proto_rawDesc), len(file_engram_proto_rawDesc)))
	})
	return file_engram_proto_rawDescData
}

var file_engram_proto_msgTypes = make([]protoimpl.MessageInfo, 19)
var file_engram_proto_goTypes = []any{
	(*MemoryRecord)(nil),          // 0: engram.v1.MemoryRecord
	(*Command)(nil),               // 1: engram.v1.Command
	(*PutCommand)(nil),            // 2: engram.v1.PutCommand
	(*CompareAndSetCommand)(nil),  // 3: engram.v1.CompareAndSetCommand
	(*DeleteCommand)(nil),         // 4: engram.v1.DeleteCommand
	(*CommandResult)(nil),         // 5: engram.v1.CommandResult
	(*MutationResult)(nil),        // 6: engram.v1.MutationResult
	(*DeleteResult)(nil),          // 7: engram.v1.DeleteResult
	(*CASConflict)(nil),           // 8: engram.v1.CASConflict
	(*PutRequest)(nil),            // 9: engram.v1.PutRequest
	(*PutResponse)(nil),           // 10: engram.v1.PutResponse
	(*GetRequest)(nil),            // 11: engram.v1.GetRequest
	(*GetResponse)(nil),           // 12: engram.v1.GetResponse
	(*CompareAndSetRequest)(nil),  // 13: engram.v1.CompareAndSetRequest
	(*CompareAndSetResponse)(nil), // 14: engram.v1.CompareAndSetResponse
	(*DeleteRequest)(nil),         // 15: engram.v1.DeleteRequest
	(*DeleteResponse)(nil),        // 16: engram.v1.DeleteResponse
	(*ListRequest)(nil),           // 17: engram.v1.ListRequest
	(*ListResponse)(nil),          // 18: engram.v1.ListResponse
	(*timestamppb.Timestamp)(nil), // 19: google.protobuf.Timestamp
}
var file_engram_proto_depIdxs = []int32{
	19, // 0: engram.v1.MemoryRecord.created_at:type_name -> google.protobuf.Timestamp
	19, // 1: engram.v1.MemoryRecord.updated_at:type_name -> google.protobuf.Timestamp
	19, // 2: engram.v1.MemoryRecord.expires_at:type_name -> google.protobuf.Timestamp
	19, // 3: engram.v1.MemoryRecord.last_accessed_at:type_name -> google.protobuf.Timestamp
	19, // 4: engram.v1.Command.timestamp:type_name -> google.protobuf.Timestamp
	2,  // 5: engram.v1.Command.put:type_name -> engram.v1.PutCommand
	3,  // 6: engram.v1.Command.compare_and_set:type_name -> engram.v1.CompareAndSetCommand
	4,  // 7: engram.v1.Command.delete:type_name -> engram.v1.DeleteCommand
	19, // 8: engram.v1.PutCommand.expires_at:type_name -> google.protobuf.Timestamp
	19, // 9: engram.v1.CompareAndSetCommand.expires_at:type_name -> google.protobuf.Timestamp
	6,  // 10: engram.v1.CommandResult.mutation:type_name -> engram.v1.MutationResult
	7,  // 11: engram.v1.CommandResult.delete_result:type_name -> engram.v1.DeleteResult
	8,  // 12: engram.v1.CommandResult.cas_conflict:type_name -> engram.v1.CASConflict
	19, // 13: engram.v1.PutRequest.expires_at:type_name -> google.protobuf.Timestamp
	0,  // 14: engram.v1.GetResponse.record:type_name -> engram.v1.MemoryRecord
	19, // 15: engram.v1.CompareAndSetRequest.expires_at:type_name -> google.protobuf.Timestamp
	0,  // 16: engram.v1.ListResponse.records:type_name -> engram.v1.MemoryRecord
	9,  // 17: engram.v1.MemoryService.Put:input_type -> engram.v1.PutRequest
	11, // 18: engram.v1.MemoryService.Get:input_type -> engram.v1.GetRequest
	13, // 19: engram.v1.MemoryService.CompareAndSet:input_type -> engram.v1.CompareAndSetRequest
	15, // 20: engram.v1.MemoryService.Delete:input_type -> engram.v1.DeleteRequest
	17, // 21: engram.v1.MemoryService.List:input_type -> engram.v1.ListRequest
	10, // 22: engram.v1.MemoryService.Put:output_type -> engram.v1.PutResponse
	12, // 23: engram.v1.MemoryService.Get:output_type -> engram.v1.GetResponse
	14, // 24: engram.v1.MemoryService.CompareAndSet:output_type -> engram.v1.CompareAndSetResponse
	16, // 25: engram.v1.MemoryService.Delete:output_type -> engram.v1.DeleteResponse
	18, // 26: engram.v1.MemoryService.List:output_type -> engram.v1.ListResponse
	22, // [22:27] is the sub-list for method output_type
	17, // [17:22] is the sub-list for method input_type
	17, // [17:17] is the sub-list for extension type_name
	17, // [17:17] is the sub-list for extension extendee
	0,  // [0:17] is the sub-list for field type_name
}

func init() { file_engram_proto_init() }
func file_engram_proto_init() {
	if File_engram_proto != nil {
		return
	}
	file_engram_proto_msgTypes[1].OneofWrappers = []any{
		(*Command_Put)(nil),
		(*Command_CompareAndSet)(nil),
		(*Command_Delete)(nil),
	}
	file_engram_proto_msgTypes[5].OneofWrappers = []any{
		(*CommandResult_Mutation)(nil),
		(*CommandResult_DeleteResult)(nil),
		(*CommandResult_CasConflict)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_engram_proto_rawDesc), len(file_engram_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   19,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_engram_proto_goTypes,
		DependencyIndexes: file_engram_proto_depIdxs,
		MessageInfos:      file_engram_proto_msgTypes,
	}.Build()
	File_engram_proto = out.File
	file_engram_proto_goTypes = nil
	file_engram_proto_depIdxs = nil
}
